{
 "title": "Rundeck",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance_address", "label": "instance_address", "query": { "query": "label_values(instance_address)" } }
  ]
 },
 "panels": [
  { "title": "RUNDECK-NOPROD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_memory_free_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_cpu_loadAverage_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rundeck_system_stats_memory_free_bytes",
     "legendFormat": "Free"
    },
    {
     "expr": "rundeck_system_stats_memory_total_bytes - rundeck_system_stats_memory_free_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "rundeck_system_stats_memory_max_bytes",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_uptime_since"
    }
   ]
  },
  {
   "title": "Scheduled Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_scheduler_quartz_scheduledJobs"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rundeck_system_stats_scheduler_running"
    }
   ]
  },
  {
   "title": "STATS: SCHEDULER",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "targets": [
    {
     "expr": "rundeck_system_stats_scheduler_running",
     "legendFormat": "RUNNING"
    },
    {
     "expr": "rundeck_system_stats_scheduler_threadPoolSize",
     "legendFormat": "THREADPOOLSIZE"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rundeck_system_stats_cpu_loadAverage_ratio",
     "legendFormat": "Load average"
    }
   ]
  }
 ]
}